language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

install:
    - composer install --prefer-dist --no-interaction --no-suggest

script:
    - vendor/bin/phpunit --verbose --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
